# Generated by Django 4.0.3 on 2022-03-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('birthday_year', models.PositiveSmallIntegerField(verbose_name='Год рождения')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Поступающий',
                'verbose_name_plural': 'Поступающие',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('min_score', models.PositiveSmallIntegerField(verbose_name='Минимальный балл')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='InternSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Балл по предмету')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_subjects', to='study.intern', verbose_name='Поступающий')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_interns', to='study.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Балл по предмету',
                'verbose_name_plural': 'Баллы по предметам',
                'unique_together': {('intern', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='intern',
            name='subjects',
            field=models.ManyToManyField(related_name='interns', through='study.InternSubject', to='study.subject', verbose_name='Предметы, которые он сдавал и баллы по ним'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('interns', models.ManyToManyField(to='study.intern', verbose_name='Поступающие')),
                ('subjects', models.ManyToManyField(related_name='directions', to='study.subject', verbose_name='Предметы, которые нужны для поступления на это направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
